theme: jekyll-theme-minimal
title: Aidan's Portfolio.
description: This page shows my projects and acomplishment with many more to come.

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge